import type { IntentType } from "../processors/types";

export interface IntentRule {
  intent: IntentType;
  patterns: RegExp[];
}

export const INTENT_RULES: IntentRule[] = [
  {
    intent: "finance",
    patterns: [
      /\b(spend|spent|spending)\b/i,
      /\b(transaction|transactions)\b/i,
      /\b(charge|charged)\b/i,
      /\b(payment|paid)\b/i,
      /\b(debit|credit)\b/i,
      /\b(bank|upi|wallet|card)\b/i,
      /\b(balance|statement)\b/i,
      /\b(expense|expenses)\b/i,
      /\b(refund|cashback)\b/i,
      /\b(salary|income)\b/i,
      /\b(emi|loan)\b/i,
      /\b(invoice|bill)\b/i,
      /how much.*(spent|spend)/i,
      /where did i spend/i,
      /recent transactions?/i,
      /did i pay/i,
      /unusual (charge|transaction)/i,
      /duplicate charge/i,
      /monthly spend/i,
    ],
  },
  {
    intent: "spending_analysis",
    patterns: [
      /\b(analyze|analysis|trend|pattern)\b/i,
      /\b(overspend|overspending)\b/i,
      /\b(cut down|reduce spending)\b/i,
      /\b(category spend)\b/i,
      /\b(compare spending)\b/i,
      /\b(month over month|week over week)\b/i,
      /\b(recurring expenses?)\b/i,
      /\b(biggest expense)\b/i,
      /\b(financial habits?)\b/i,
      /what am i spending most on/i,
      /\b(spending increase)\b/i,
    ],
  },
  {
    intent: "scheduling",
    patterns: [
      /\b(meeting|meetings)\b/i,
      /\b(calendar|schedule)\b/i,
      /\b(appointment|event)\b/i,
      /\b(today|tomorrow)\b/i,
      /\b(this week|next week)\b/i,
      /\b(upcoming)\b/i,
      /\b(availability|free time)\b/i,
      /\b(reschedule)\b/i,
      /\b(call with)\b/i,
      /\b(agenda)\b/i,
      /\b(check.?in)\b/i,
      /what.*(today|tomorrow)/i,
      /do i have anything/i,
      /when is my/i,
    ],
  },
  {
    intent: "commitments",
    patterns: [
      /\b(commitment|commitments)\b/i,
      /\b(promise|promised)\b/i,
      /\b(committed)\b/i,
      /i said i would/i,
      /\b(deadline|due)\b/i,
      /\b(follow through)\b/i,
      /what did i say/i,
      /\b(pending)\b/i,
      /\b(outstanding)\b/i,
      /\b(overdue)\b/i,
      /what did i (promise|commit)/i,
      /did i tell.*i would/i,
      /what am i forgetting/i,
    ],
  },
  {
    intent: "productivity",
    patterns: [
      /\b(task|tasks)\b/i,
      /\b(todo|to-do)\b/i,
      /\b(action item|action items)\b/i,
      /\b(priority|priorities)\b/i,
      /\b(focus on)\b/i,
      /\b(blocked|blockers)\b/i,
      /\b(next step|next steps)\b/i,
      /\b(work on)\b/i,
      /\b(unfinished)\b/i,
      /what should i.*do/i,
      /what needs attention/i,
      /what is urgent/i,
      /what am i missing/i,
    ],
  },
  {
    intent: "relationship",
    patterns: [
      /\b(follow.?up)\b/i,
      /\b(reconnect)\b/i,
      /\b(reply to)\b/i,
      /\b(investor|client|customer|partner)\b/i,
      /\b(networking)\b/i,
      /\b(relationship)\b/i,
      /\b(last spoke)\b/i,
      /\b(waiting on)\b/i,
      /\b(no response)\b/i,
      /who haven.t i/i,
      /who do i need to follow up with/i,
      /when did i last talk/i,
      /\b(stakeholder|stakeholders)\b/i,
      /\b(communication|communications)\b/i,
    ],
  },
  {
    intent: "travel",
    patterns: [
      /\b(flight|flights)\b/i,
      /\b(hotel|booking)\b/i,
      /\b(trip|travel)\b/i,
      /\b(pnr|boarding)\b/i,
      /\b(airline|airport)\b/i,
      /\b(train|bus)\b/i,
      /\b(itinerary)\b/i,
      /\b(reservation)\b/i,
      /\b(vacation)\b/i,
      /\b(travel plan)\b/i,
    ],
  },
  {
    intent: "search_lookup",
    patterns: [
      /\b(find|search)\b/i,
      /\b(look up)\b/i,
      /\b(show me)\b/i,
      /\b(what did)\b/i,
      /\b(when did)\b/i,
      /\b(email about)\b/i,
      /\b(note about)\b/i,
      /\b(conversation about)\b/i,
      /\b(receipt for)\b/i,
      /\b(document)\b/i,
      /find (the|my)? (email|note)/i,
      /what was discussed/i,
      /did i receive/i,
    ],
  },
  {
    intent: "operational_summary",
    patterns: [
      /\b(brief|briefing)\b/i,
      /\b(summary|summarize)\b/i,
      /\b(overview|status)\b/i,
      /\b(catch me up)\b/i,
      /\b(what matters)\b/i,
      /\b(anything important)\b/i,
      /\b(highlights)\b/i,
      /\b(daily update)\b/i,
      /\b(weekly review)\b/i,
      /what (happened|changed)/i,
      /\b(operational (goal|goals|target|targets|record|records|metric|metrics|review|reviews|report|reports|summary|summaries|insight|insights))\b/i,
      /\b(operation (record|records|review|reviews))\b/i,
      /\b(summaries)\b/i,
    ],
  },
  {
    intent: "subscriptions",
    patterns: [
      /\b(subscription|subscriptions)\b/i,
      /\b(recurring)\b/i,
      /\b(renewal|renew)\b/i,
      /\b(monthly charge)\b/i,
      /\b(cancel)\b/i,
      /\b(auto.?pay)\b/i,
      /\b(membership)\b/i,
      /\b(annual plan)\b/i,
      /what subscriptions/i,
      /am i paying for/i,
    ],
  },
  {
    intent: "bills_payments",
    patterns: [
      /\b(bill|bills)\b/i,
      /\b(payment due)\b/i,
      /\b(due date)\b/i,
      /\b(credit card)\b/i,
      /\b(electricity|internet|rent)\b/i,
      /\b(utility)\b/i,
      /\b(emi)\b/i,
      /\b(outstanding payment)\b/i,
      /\b(overdue payment)\b/i,
      /what do i need to pay/i,
      /upcoming bills/i,
    ],
  },
  {
    intent: "reminders",
    patterns: [
      /\b(remind|reminder)\b/i,
      /don.t let me forget/i,
      /\b(remember to)\b/i,
      /\b(alert me)\b/i,
      /\b(remind me)\b/i,
    ],
  },
];
