export const CATEGORIES = [
  { key: "important",                label: "Important",              icon: "★" },
  { key: "pending_reply",            label: "Pending Reply",          icon: "↩" },
  { key: "finance_bills",            label: "Finance & Bills",        icon: "₹" },
  { key: "transactions",             label: "Transactions",           icon: "🧾" },
  { key: "subscriptions_memberships", label: "Subscriptions",         icon: "♻" },
  { key: "receipts_documents",       label: "Receipts & Docs",        icon: "📄" },
  { key: "legal_government",         label: "Legal & Gov",            icon: "⚖" },
  { key: "meetings_calendar",        label: "Meetings",               icon: "📅" },
  { key: "shipping_orders",          label: "Shipping & Orders",      icon: "📦" },
  { key: "productivity_tools",       label: "Productivity",           icon: "⚙" },
  { key: "career",                   label: "Career",                 icon: "💼" },
  { key: "social",                   label: "Social",                 icon: "💬" },
  { key: "newsletters",              label: "Newsletters",            icon: "📰" },
  { key: "news",                     label: "News",                   icon: "📡" },
  { key: "learning",                 label: "Learning",               icon: "🎓" },
  { key: "entertainment",            label: "Entertainment",          icon: "🎬" },
  { key: "fitness",                  label: "Fitness & Health",       icon: "🏃" },
  { key: "system_notifications",     label: "System",                 icon: "🔔" },
  { key: "account_security",         label: "Account & Security",     icon: "🔒" },
  { key: "travel",                   label: "Travel",                 icon: "✈" },
  { key: "promotions",               label: "Promotions",             icon: "%" },
  { key: "other",                    label: "Other",                  icon: "•" },
];
